[package]
name = "tutorial1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
word_generator = "0.1.1"
unicode-segmentation = "1.9.0"
rand = "0.8.5"